### ISSUE TITLE
Некорректная документация по настройке иерархии в лукапе

### ISSUE THREAD

**Issue by jbzorg** [Flexberry/flexberry.github.io#104]
В [документации](https://flexberry.github.io/ru/fe_lookup-component.html#%D0%BD%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B9%D0%BA%D0%B0-%D0%B8%D0%B5%D1%80%D0%B0%D1%80%D1%85%D0%B8%D0%B8) по настройке иерархического отображения в лукапе есть смысл внести следующие изменения:

1. Отметить, что `getLookupFolvProperties` - это экшн и, соотвественно, должен находиться в объекте `actions`. Из документации это не очевидно.
2. Не достаточно вернуть объект:
```js
  {
    disableHierarchicalMode: false,
    inHierarchicalMode: true,
    hierarchicalAttribute: 'Name'
  }
```
Необходимо расширить объект, возвращаемый базовым `getLookupFolvProperties`.
Например (в данном случае, используется отдельный экшен):
```js
  actions: {
    getLookupFolvPropertiesPeriod: function(options) {
      return $.extend(true, this.getLookupFolvProperties(options), {
        inHierarchicalMode: true, // Активировать иерархию при загрузке lookup-формы.
        hierarchicalAttribute: 'ierarhiia' // Свойство, по которому строится иерархия.
      });
    }
  }
```

**Comment by KollegOFF** [comment]
Метод `getLookupFolvProperties` не определяется в классах из `ember-flexberry`, есть экшен в контроллерах с примерами использования компонента, но они не доступны вне `ember-flexberry`.
Возможно, в качестве базового контроллера, использовался контроллер не из `ember-flexberry`?
