### ISSUE TITLE
Релевантный поиск по документации

### ISSUE THREAD

**Issue by bratchikov** [Flexberry/flexberry.github.io#15]
Реализовать качественный и релевантный поиск по документации. Пользователь должен по типичным ключевым словам находить нужные статьи. Ввиду того, что поддержка ключевых слов для каждой статьи - это дело сложное, предлагается реализовать такой поиск, который будет учитывать и основной текст. Для руководства по EmberJS используют вот этот продукт (бесплатно для open source): https://www.algolia.com/products/search . Предлагается проанализировать это решение.

**Comment by savolkov** [comment]
Подал заявку вот сюда https://community.algolia.com/docsearch/

**Comment by savolkov** [comment]
Завёл задачу на вёрстку: #26
