### ISSUE TITLE
Изменить соглашение об адресах статей

### ISSUE THREAD

**Issue by KollegOFF** [Flexberry/flexberry.github.io#25]
Использовать полное название, вместо сокращения, в адресах статей.
Напрмер, `flexberry-orm-` вместо `fo_`, `flexberry-designer-` вместо `fd_`, и т.д.

**Comment by Nasutya** [comment]
Это точно не вариант. Перегружает очень сильно. Я наоборот за максимально короткое название статьи. Излишне длинные переименовываю.

**Comment by KollegOFF** [comment]
Префиксы просто уродско выглядят.
