### ISSUE TITLE
Документация компонента flexberry-groupedit

### ISSUE THREAD

**Issue by KollegOFF** [Flexberry/flexberry.github.io#47]
Нужно создать статью с описанием компонента `{{flexberry-groupedit}}` из [ember-flexberry](https://github.com/Flexberry/ember-flexberry).
Статью добавить в сайдбар [flexberry-ember](https://github.com/Flexberry/flexberry.github.io/blob/master/_data/sidebars/flexberry-ember_sidebar.yml), в новый раздел `Компоненты`.

Предлагаю начать с объединения всех статей из раздела `ember-flexberry » Groupedit`, возможно потом, некоторые темы, можно будет выделить в отдельные статьи.
Нужно учесть что компонент составной, и использует другие компоненты.

В комментариях компонентов для авто-документации, добавить ссылки на статьи.
При написании статьи не забывайте сверяться с [рекомендациями](https://flexberry.github.io/ru/fp_documentation-writing-guidelines.html).

**Comment by Nasutya** [comment]
Выполнено: https://flexberry.github.io/ru/fe_groupedit.html
