### ISSUE TITLE
Написать глоссарий

### ISSUE THREAD

**Issue by KollegOFF** [Flexberry/flexberry.github.io#51]
Есть [пустой глоссарий](https://github.com/Flexberry/flexberry.github.io/blob/master/pages/products/flexberry-platform/fp_Glossary.ru.md), его нужно наполнить основными терминами и добавить в сайдбар.

**Comment by Nasutya** [comment]
Глоссарий заполнен самыми базовыми понятиями, будет пополняться по мере необходимости.
